language: scala
matrix:
  include:
  matrix:
  include:
    - env: OSX=10.11
      os: osx
      osx_image: osx10.11
      rvm: system
      scala: 2.11.8
      script: sbt clean coverage test coverageReport
   -os:linux
    scala: 2.11.8
    script: sbt clean coverage test coverageReport
    after_success:bash <(curl -s https://codecov.io/bash)
#jdk:
#- oraclejdk7




