language: scala
scala: 2.11.8
matrix:
  include:
    - env: OSX=10.11
      os: osx


script:
- sbt clean coverage test coverageReport

after_success:
- bash <(curl -s https://codecov.io/bash)  
    
      






