dist: trusty
language: scala
os:
  - linux
  
scala:
  - 2.12.11

jdk:
- oraclejdk8

before_script:
- git config --global github.token SOME_TOKEN

script:
- sbt compile 

after_success:
- bash <(curl -s https://codecov.io/bash)

      






